#!/usr/bin/python3
from signal import signal, SIGTERM, SIGHUP, pause
from subprocess import Popen, PIPE
from time import sleep
from datetime import datetime
from rpi_lcd import LCD
import subprocess
import time

lcd = LCD(address=0x27,bus=1)

# looking for an active Ethernet or WiFi device
def find_interface():
    find_device = "ip addr show"
    interface_parse = run_cmd(find_device)
    for line in interface_parse.splitlines():
        if "state UP" in line:
            dev_name = line.split(':')[1]
    return dev_name

# find an active IP on the first LIVE network device
def parse_ip():
    find_ip = "ip addr show %s" % interface
    find_ip = "ip addr show %s" % interface
    ip_parse = run_cmd(find_ip)
    for line in ip_parse.splitlines():
        if "inet " in line:
            ip = line.split(' ')[5]
            ip = ip.split('/')[0]
    return ip

# run unix shell command, return as ASCII
def run_cmd(cmd):
    p = Popen(cmd, shell=True, stdout=PIPE)
    output = p.communicate()[0]
    return output.decode('ascii')

# wipe LCD screen before we start
lcd.clear()

# before we start the main loop - detect active network device and ip address
sleep(2)
interface = find_interface()
ip_address = parse_ip()

while True:

    # date and time
     lcd.text(datetime.now().strftime('%b %d  %H:%M:%S\n'),1)

    # current ip address
     lcd.text("IP " + ip_address,2)

    # combine both lines into one update to the display
    ##lcd.message = lcd_line_1 + lcd_line_2
    
     sleep(1)

##lcd.clear()